package exception_handling;

public class HandleExe {

	public static void main(String[] args) {
		HandleExe e = null; 
		String s = null;
		try {
//			int i = 1/0;//new Arithmeticexecption("/zero")
//			int[] i = {1,2,3,3}; 
//			System.out.println("hello");
//			System.out.println(i[4]);
			System.out.println(e);
			System.out.println(s.length());
			
		}

		catch(Exception e1) {
			System.out.println("exc");
		}
		
//		catch(ArithmeticException e) {
//			System.out.println("arith");
//		}
		
//		catch(ArrayIndexOutOfBoundsException e) {
//			System.out.println("i exc");
//		}
		
		
	}

}
